spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-db
    username: root
    password: Admin22@mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
